Repository TimoGlastra/aries-mobile-agent-react-native, pull requests merged in 2020-12, with the labels that each got.

#1 Resolved unsupported getRandomValues error
  package.json
  src/App.tsx
Labels: bug

#4 add usage documentation
  CONTRIBUTING.md
  LICENSE
  README.md
  images/aries-logo.png
  src/App.tsx
  src/agentInit.ts
Labels: documentation

#5 Implemented agent connection establishment
  src/App.tsx
  src/components/connection.tsx
Labels: enhancement

#6 Connection via Invitation URL
  src/App.tsx
Labels: enhancement

#7 Added support to display Credentials
  src/App.tsx
  src/components/credential.tsx
Labels: enhancement

#12 Updated aries-framework-javascript
  aries-framework-javascript-v1.0.0.tgz
Labels: enhancement

#13 Added Issue & Accept credential functionality
  src/App.tsx
  src/agentInit.ts
  src/components/connection.tsx
  src/components/credential.tsx
Labels: enhancement
